//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.AllProductImages = new HashSet<AllProductImage>();
            this.Categories = new HashSet<Category>();
            this.FeaturedSuppliers = new HashSet<FeaturedSupplier>();
            this.ProductAttributesRelations = new HashSet<ProductAttributesRelation>();
            this.ProductImages = new HashSet<ProductImage>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string Logo { get; set; }
        public string SupplierType { get; set; }
        public int ParentSupplierID { get; set; }
        public string RegisteredByID { get; set; }
        public string UserID { get; set; }
        public int PlanID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Sort { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public System.DateTime PlanStartDate { get; set; }
        public System.DateTime PlanEndDate { get; set; }
        public int ProductCount { get; set; }
        public int UserCount { get; set; }
    
        public virtual ICollection<AllProductImage> AllProductImages { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<FeaturedSupplier> FeaturedSuppliers { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual ICollection<ProductAttributesRelation> ProductAttributesRelations { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
